---

  - name: Create user tolq16 and private/public keys
    user:
      name: tolq16
      groups: postgres,sudo
      password: "{{ tolq16_password }}"
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_comment: "ansible-generated for tolq16@{{ ansible_hostname }}"

  - name: Create user postgres01 and private/public keys
    user:
      name: postgres01
      password: "{{ postgres01_password }}"
      shell: /bin/bash
      groups:
       - postgres
       - sudo
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_comment: "ansible-generated for postgres01@{{ ansible_hostname }}"

# Directory ssh_public_keys locate in the same directory as playbook file
  - name: Fetch the keyfile from the node to master
    fetch:
      src: /home/{{ item }}/.ssh/id_rsa.pub
      dest: ssh_public_keys/{{inventory_hostname}}-{{ item }}-id_rsa.pub
      flat: yes
    with_items:
      - tolq16
      - postgres01

  - name: Copy the key add to authorized_keys using Ansible module
    authorized_key:
      user: tolq16
      state: present
      key: "{{ lookup('file','ssh_public_keys/{{inventory_hostname}}-{{ item }}-id_rsa.pub') }}"
    with_items:
      - tolq16
      - postgres01
