---
- name: Exchange Keys between servers
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Fetch the keyfile from the node to master
      fetch:
        src: /home/tolq15/.ssh/id_rsa.pub
        dest: ssh_public_keys/{{inventory_hostname}}-tolq15-id_rsa.pub
        flat: yes

    - name: Copy the key add to authorized_keys using Ansible module
      authorized_key:
        user: tolq15
        state: present
        key: "{{ lookup('file','ssh_public_keys/{{ item }}-tolq15-id_rsa.pub') }}"
      with_items:
        - "{{ groups['all'] }}"
